### ISSUE TITLE
The apisix-seed will fail to load discovery configuration when the nacos password contains special characters

### ISSUE THREAD

**Issue by seek0608** [api7/apisix-seed#61]
When the password of nacos is ‘xQ+/OfYv+q’, the apisix-seed will not start.

![image](https://user-images.githubusercontent.com/50513960/203685727-69ea2ccf-d96b-43c0-b9ea-542b2c792ef0.png)

```
discovery:
  nacos:
    host:
      - "http://reader:xQ+/OfYv+q@nacos.com:80"
    prefix: /nacos
    weight: 100
    timeout:
      connect: 2000
      send: 2000
      read: 5000
```

I hope that the account and password will try a new field for configuration.
